import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F9FF;',
    alignItems: 'center',
  },
  SelectInput: {
    width: width * 0.9,
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    backgroundColor: '#FFF',
    elevation: 1,
  },
  cardContainer: {
    margin: 0,
    marginBottom: 14,
    padding: 0,
    borderRadius: 10,
    width: width * 0.92,
    elevation: 2,
    borderStartWidth: 4,
    borderStartColor: '#7FE37D',
  },
  button: {
    backgroundColor: '#4577EF',
    width: width * 0.146,
    paddingVertical: 10,
    borderRadius: 100,
    marginTop: 16,
    position: 'absolute',
    bottom: 30,
    right: 20,
    elevation: 3,
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 24,
  },
  scrollViewContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 4,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 6,
    marginRight: 10,
    paddingHorizontal: 15,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterIcon: {
    marginLeft: 10,
  },
  filterModalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  filterModal: {
    backgroundColor: '#F6F9FF',
    padding: 20,
    borderRadius: 10,
    width: width, // Set width to full width
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  closeButton: {
    position: 'absolute',
    top: 14,
    right: 10,
  },
  modalHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#43436A',
    marginBottom: 20,
  },
  filterOptionsContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  filterText: {
    color: '#43436A',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  applyButton: {
    backgroundColor: '#4577EF',
    padding: 14,
    borderRadius: 5,
    marginTop: 16,
  },
  cancelButton: {
    backgroundColor: '#F0F0F0',
    padding: 14,
    borderRadius: 5,
    marginTop: 16,
    color: '#667080',
  },
  cancelButtonText: {
    color: '#667080',
    textAlign: 'center',
  },
  applyButtonText: {
    color: 'white',
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#FFF',
    borderRadius: 5,
    marginVertical: 10,
    padding: 12,
    elevation: 1,
  },
  cardContents: {
    padding: 15,
    width: width * 0.9,
  },
  itemNumber: {
    fontSize: 14,
    color: '#43436A',
    fontWeight: '500',
    paddingRight: 15,
    marginBottom: 5,
  },
  itemValue: {
    fontSize: 12,
    fontWeight: '400',
    color: '#43436A',
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statusRows: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  statusLabel: {
    fontSize: 12,
    color: '#AAA',
  },
  statusValue: {
    fontSize: 12,
    color: 'green',
    backgroundColor: '#BAEDD1',
    borderRadius: 14,
    padding: 2,
    paddingStart: 8,
    paddingEnd: 8,
  },
  statusValues: {
    fontSize: 12,
    color: '#2D2D30',
    borderWidth: 0.5,
    borderRadius: 8,
    padding: 2,
    paddingStart: 8,
    paddingEnd: 8,
  },
  statusSubValue: {
    fontSize: 12,
    color: '#2D2D30',
    borderWidth: 0.5,
    borderRadius: 8,
    marginStart: 4,
    padding: 2,
    paddingStart: 8,
    paddingEnd: 8,
  },
});
